### ISSUE TITLE
brainstorm how to connect BLISS with JIF (inputs/outputs)

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/bayesian-pipelines-pixels#14]
Resources: 
- Synergies with BLISS [slides](https://docs.google.com/presentation/d/1i4pEKnkp9P1MfSNxpNeGnrOxB64LvJjmMOWgJz4wC-M/edit?usp=sharing)
- Brainstorm [document](https://docs.google.com/document/d/190KGDv83fjmuHBG-bLAo64YDtW7f8wIeZo3zXgym_Os/edit#)

**Comment by mdschneider** [comment]
From @ismael-mendoza 's slides, two options for interfacing BLISS and JIF / MBI-Shear stand out to me:
1. The number of galaxies in a footprint is sampled from BLISS outputs and input to JIF fitting of the footprint
2. Samples of galaxy parameters from BLISS can be fed into the MBI-Shear hierarchical inference stage to infer shear (so that BLISS functionally replaces JIF in the pipeline).

JIF requires an asserted number of galaxies in a footprint, so option 1 above will be a requirement for any pipeline including JIF.

Option 2 suggests a possibility for benchmarking BLISS and JIF image analyses with a performance metric that could be shear multiplicative and additive biases (as in GREAT3) as well as runtime.

**Comment by ismael-mendoza** [comment]
In terms of connecting to `MBI-Shear`, one thing we discussed today was that we can take samples from BLISS on ellipticities for each object and directly feed them to it.
