### ISSUE TITLE
add more realistic distributions for generating synthetic catalogs

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/bayesian-pipelines-pixels#25]
could be useful in development and to test things quickly, but I think we will mostly use DC2 catalogs to sample

**Comment by jjbuchanan** [comment]
Lately I've been studying what I'm calling "isolated" footprints in DC2 i-band coadd images, which are footprints containing one true galaxy or star with brightness exceeding 50 times the sum of anything else in the footprint. The distribution of observable parameters for objects detected in such footprints is described by the following values:
```
prior_mean_hlrFlux = np.array([-0.72972787,  0.67149507]) # log pixels, log inst flux
prior_inv_cov_hlrFlux = np.array([[ 3.26319582, -1.15157345],
       [-1.15157345,  1.73425812]])
prior_lap_e1e2 = 0.20561431640099914
```
The first is the mean of the log-hlr (in log-pixels) and log-flux (in log-instrumental flux counts)
The second is the inverse covariance matrix between log-hlr and log-flux
and the third is the characteristic width of a Laplace distribution for e1 and for e2, in the "distortion" convention where |e| = (a\*\*2 - b\*\*2) / (a\*\*2 + b\*\*2) [the same as GalSim's definition of e]

Again, among objects in these isolated footprints, hlr and flux are distributed in a fairly nice 2-D Gaussian with the above parameters.
Note that very dim galaxies are extremely under-weighted in this model, since they're less likely to be detected. Very bright galaxies are also under-weighted since they're less likely to be isolated (i.e. the only significant galaxy in their footprint).

The other obvious caveat is that no distinction is made between bulge and disk components. One simplistic option is to assign all the flux to bulge and all the flux to disk with 50/50 probability, which is a rough but not outrageous approximation of the actual distribution in cosmoDC2.

The Laplace distribution with the width given above matches the tails of the actual e1 and e2 distributions, but is noticeably wider than the true distribution near e1,e2 = 0. This could be considered a somewhat "conservative" prior, but much closer to the truth than a flat prior.

I'm currently looking at the distributions of bulge size/ellipticity, disk size/ellipticity, total flux, and disk flux ratio for all galaxies in cosmoDC2 without any constraints, which would be a more appropriate prior for general scene drawing. But if you're just interested in sampling objects that would be truly unblended in a typical 5-year i-band coadd, the above is a reasonable model.

**Comment by ismael-mendoza** [comment]
- Axel: GREAT3 Challenge, try to model correlations with parameters - paper from Rachel. Pull from Galsim repo ? look at GREAT3 tutorial?
